import os
import json
from fastapi import APIRouter, HTTPException
from pydantic import BaseModel
from typing import List, Optional, Dict, Any

from services.llm_client import call_openrouter
from kb.kb_loader import load_kb

router = APIRouter()

# ──────────────────────────────────────────────────────────────────────────────
# SYNTHESIS SYSTEM PROMPT — Loaded from KB
# Generates Artifact 1 (Strategic Research Brief)
# ──────────────────────────────────────────────────────────────────────────────

def _get_brief_system_prompt() -> str:
    """Load the brief synthesis prompt from KB."""
    return load_kb("agents/brief_agent.md")


class PillarScore(BaseModel):
    label: str
    score: int

class BriefRequest(BaseModel):
    research_intent: str
    parameters: List[PillarScore]
    pillar_extractions: Optional[Dict[str, Any]] = None
    context_document: Optional[str] = None
    template: Optional[str] = None
    hypothesis_manifest: Optional[Dict[str, Any]] = None

class BriefResponse(BaseModel):
    brief: str


@router.post("/generate-brief", response_model=BriefResponse)
def generate_strategic_brief(request: BriefRequest):
    """
    Synthesis Layer: converts structured pillar extractions into
    Artifact 1 (Strategic Research Brief .md) using the spec-compliant prompt.
    """
    try:
        # Build rich user prompt using pillar extractions
        pillar_block = "\n".join(
            f"- **{p.label}** (Score: {p.score}/100)" for p in request.parameters
        )

        extractions_block = ""
        if request.pillar_extractions:
            extractions_block = f"\n\n### Structured Pillar Extractions (PRIMARY DATA SOURCE)\n```json\n{json.dumps(request.pillar_extractions, indent=2)}\n```\nCRITICAL: Use the SPECIFIC data in these extractions (competitor names, timelines, hypotheses, geographic scope) to populate every section of the brief. Do NOT use generic placeholders."

        context_block = ""
        if request.context_document:
            context_block = f"\n\n### Uploaded Research Context\n```\n{request.context_document[:2000]}\n```"

        template_block = ""
        if request.template and request.template != "none":
            template_block = f"\n\n**Study Type / Archetype:** {request.template}"

        user_prompt = f"""## Client Intake Summary

**North Star Research Intent:**
{request.research_intent}
{template_block}

**Diagnostic Pillar Scores:**
{pillar_block}
{extractions_block}
{context_block}

---

Please synthesize the above intake into a full Strategic Research Brief following the required output structure.
Use the exact data from pillar_extractions to populate each section. Do NOT invent data that was not provided.
"""

        # ── HYPOTHESIS MANIFEST INJECTION ──
        if request.hypothesis_manifest:
            manifest_block = (
                "\n\n### Pre-Generated Hypothesis Manifest (RENDER, DO NOT REGENERATE)\n"
                "CRITICAL INSTRUCTION: The hypotheses below were generated by the Hypothesis Engine. "
                "You MUST render them exactly as provided in the \"Hypotheses to Stress-Test\" section of the brief. "
                "Do NOT generate alternative hypotheses. Preserve all hypothesis IDs (h_001, h_002, etc.) verbatim. "
                "Structure: one subsection per core_problem, contrarian pairs rendered adjacent (side-by-side or back-to-back). "
                "Each hypothesis paragraph must include: statement, dimension, force assignment, expected signals, and rationale.\n"
                "```json\n" + json.dumps(request.hypothesis_manifest, indent=2)[:8000] + "\n```"
            )
            user_prompt += manifest_block

        brief_text = call_openrouter(
            system_prompt=_get_brief_system_prompt(),
            user_prompt=user_prompt,
            expect_json=False,
            model="google/gemini-pro-1.5-exp:free"
        )

        # Save Artifact 1 to disk
        with open("Strategic_Brief.md", "w") as f:
            f.write(f"# Outtlyr Strategic Research Brief\n\n")
            f.write(f"**Research Intent:** {request.research_intent}\n\n")
            f.write("---\n\n")
            f.write(brief_text)

        # ── DEV BYPASS CAPTURE: Save snapshot of this run ──
        import pathlib
        capture_dir = pathlib.Path("latest_run_data")
        capture_dir.mkdir(exist_ok=True)
        (capture_dir / "latest_intent.txt").write_text(request.research_intent, encoding="utf-8")
        (capture_dir / "latest_brief.md").write_text(brief_text, encoding="utf-8")

        return BriefResponse(brief=brief_text)

    except ValueError as e:
        if "OPENROUTER_API_KEY" in str(e):
            raise HTTPException(status_code=500, detail="Missing API Key.")
        raise HTTPException(status_code=500, detail=str(e))
    except Exception as e:
        raise HTTPException(status_code=500, detail=str(e))
