import os
import json
from fastapi import APIRouter, HTTPException
from pydantic import BaseModel
from typing import List, Dict, Any, Optional
import networkx as nx

from services.llm_client import call_openrouter
from kb.kb_loader import load_kb
from services.force_taxonomy import force_label

router = APIRouter()

class IntentPayload(BaseModel):
    intent: str
    brief: str | None = None
    hypothesis_manifest: Optional[Dict[str, Any]] = None

# We no longer use a fixed list of forces; categories are dynamically derived from the intent/brief.



def _get_ecosystem_generic_prompt() -> str:
    """Load the generic ecosystem prompt from KB."""
    return load_kb("agents/ecosystem_generic_agent.md")

def _get_ecosystem_brief_prompt() -> str:
    """Load the brief-driven ecosystem prompt from KB."""
    return load_kb("agents/ecosystem_brief_agent.md")


def generate_dynamic_ecosystem_graph(
    intent: str,
    brief: str | None = None,
    hypothesis_manifest: Optional[Dict[str, Any]] = None,
) -> Dict[str, Any]:
    """Build the Category Graph.

    When `hypothesis_manifest` is supplied (non-None and contains `core_problems`),
    the graph hierarchy becomes:

        root (core_topic)
          ├── core_problem_<cp.id>            (color #a855f7, size 5)
          │     └── hypothesis_anchor_<h.id>  (color #6366f1, size 6)
          │           └── subjects/components/signals (LLM-generated)
          ├── core_problem_<cp.id>
          │     └── hypothesis_anchor_<h.id>
          └── scope_nodes (still attached to root)

    Subjects/components/signals are generated by the existing LLM pipeline and
    attached under the FIRST hypothesis_anchor of the FIRST core problem.

    NOTE — KNOWN SIMPLIFICATION: For this first pass, all generated subjects
    hang off a single anchor. This is acceptable for graphs with one core
    problem and a small number of hypotheses; when multiple core problems are
    present a future revision should distribute subjects across the relevant
    anchors based on hypothesis dimension/force, instead of dumping the entire
    subject hierarchy under the first anchor.

    When `hypothesis_manifest` is None or has no core_problems, the original
    behaviour is preserved: subjects/components/signals attach directly to root.
    """
    try:
        if brief:
            system_prompt = _get_ecosystem_brief_prompt()
            user_prompt = (
                f"Research Intent: {intent}\n\n"
                f"=== STRATEGIC RESEARCH BRIEF (PRIMARY SOURCE) ===\n"
                f"{brief[:7000]}\n"
                f"=== END BRIEF ===\n\n"
                f"Now generate the Category Graph JSON by mapping the brief's tiers, units, signals, and sources directly to the 5 Strategic Forces.\n"
                f"Every node must be a named entity, platform, signal, or source from the brief above."
            )
        else:
            system_prompt = _get_ecosystem_generic_prompt()
            user_prompt = f"Map the ecosystem for this research intent: {intent}"

        llm_result = call_openrouter(
            system_prompt=system_prompt, 
            user_prompt=user_prompt, 
            expect_json=True,
            model="mistralai/mistral-7b-instruct:free"
        )
        
        G = nx.DiGraph()
        
        core_topic = llm_result.get("core_topic", "Core Subject")
        G.add_node(core_topic, type="root", label=core_topic, force="root", description="The central business problem driving this research study.")

        # ── Hypothesis Anchors: insert core_problem and hypothesis_anchor nodes ──
        first_anchor_id: Optional[str] = None
        manifest_active = bool(
            hypothesis_manifest and hypothesis_manifest.get("core_problems")
        )
        anchors_by_force = {}

        if manifest_active:
            for cp in hypothesis_manifest["core_problems"]:
                cp_node_id = f"core_problem_{cp['id']}"
                G.add_node(
                    cp_node_id,
                    type="core_problem",
                    label=cp.get("statement", cp["id"])[:80],
                    color="#a855f7",
                    size=5,
                    priority=cp.get("priority", "primary"),
                    force="root",
                    description=cp.get("statement", ""),
                )
                G.add_edge(core_topic, cp_node_id)

                for h in cp.get("hypotheses", []):
                    anchor_id = f"hypothesis_anchor_{h['id']}"
                    force_name = force_label(h.get("force_assignment", ""))
                    if force_name not in anchors_by_force:
                        anchors_by_force[force_name] = anchor_id

                    G.add_node(
                        anchor_id,
                        type="hypothesis_anchor",
                        label=h.get("statement", h["id"])[:80],
                        color="#6366f1",
                        size=6,
                        hypothesis_id=h["id"],
                        dimension=h.get("dimension"),
                        force=force_name,
                        contrarian_pair_id=h.get("contrarian_pair_id"),
                        description=h.get("rationale", ""),
                    )
                    G.add_edge(cp_node_id, anchor_id)
                    if first_anchor_id is None:
                        first_anchor_id = anchor_id

        # ── Tier 5: Scope nodes (geography, timeline, cohort) → attach to root ──
        # Scope nodes always hang off root, regardless of whether a manifest is supplied.
        for scope in llm_result.get("scope_nodes", []):
            scope_name = scope.get("name", "Unknown Scope")
            scope_type = scope.get("type", "scope")
            scope_force = scope.get("force_metadata", "Demand Gravity")
            scope_desc = scope.get("description", f"Study boundary: {scope_type}")
            G.add_node(scope_name, type="scope", label=scope_name, force=scope_force, scope_type=scope_type, subject="root", description=scope_desc)
            G.add_edge(core_topic, scope_name)

        # ── Tier 1-4: Subjects → Components → Signals → Context Nodes ──
        subjects = llm_result.get("subjects", [])
        if not subjects and "categories" in llm_result: # fallback
            subjects = llm_result.get("categories", [])
            
        for subject in subjects:
            subj_name = subject.get("name", subject.get("category_name", "Unknown Subject"))
            subj_force = subject.get("force_metadata", "Demand Gravity")
            
            if manifest_active:
                # Map subject to the hypothesis anchor matching its force, fallback to first anchor
                subject_parent = anchors_by_force.get(subj_force, first_anchor_id)
            else:
                subject_parent = core_topic

            subj_desc = subject.get("description", "")
            
            G.add_node(subj_name, type="subject", label=subj_name, force=subj_force, subject=subj_name, description=subj_desc)
            G.add_edge(subject_parent, subj_name)
            
            # Tier 2: Components
            components = subject.get("components", [])
            if not components and "nodes" in subject: # fallback handling
                components = [{"name": n, "force_metadata": subj_force, "signals": []} for n in subject.get("nodes", [])]
                
            for comp in components:
                comp_name = comp.get("name", "Unknown Component")
                comp_force = comp.get("force_metadata", "Demand Gravity")
                comp_desc = comp.get("description", "")
                G.add_node(comp_name, type="component", label=comp_name, force=comp_force, subject=subj_name, description=comp_desc)
                G.add_edge(subj_name, comp_name)
                
                # Tier 3: Signals
                for sig in comp.get("signals", []):
                    sig_name = sig.get("name", "Unknown Signal")
                    sig_force = sig.get("force_metadata", "Demand Gravity")
                    sig_desc = sig.get("description", "")
                    G.add_node(sig_name, type="signal", label=sig_name, force=sig_force, subject=subj_name, description=sig_desc)
                    G.add_edge(comp_name, sig_name)
            
            # Tier 4: Context nodes (rivals, triggers) → attach to subject
            for ctx in subject.get("context_nodes", []):
                ctx_name = ctx.get("name", "Unknown Context")
                ctx_type = ctx.get("type", "context")
                ctx_force = ctx.get("force_metadata", "Competitive Energy")
                ctx_desc = ctx.get("description", f"{ctx_type.replace('_', ' ').title()} relevant to this hypothesis.")
                # Avoid duplicate node IDs by prefixing if needed
                node_id = ctx_name if ctx_name not in G else f"{ctx_name} ({subj_name[:10]})"
                G.add_node(node_id, type="context", label=ctx_name, force=ctx_force, context_type=ctx_type, subject=subj_name, description=ctx_desc)
                G.add_edge(subj_name, node_id)
                
        data = nx.node_link_data(G)
        data["links"] = data.get("edges", [])
        if "edges" in data:
            del data["edges"]
        return data
        
    except Exception as e:
        G = nx.DiGraph()
        err_msg = "Missing API Key" if "OPENROUTER_API_KEY" in str(e) else "LLM Generation Failed"
        G.add_node(err_msg, type="root", label=err_msg, force="root")
        G.add_node(str(e)[:50], type="category", label=str(e)[:50], force="error")
        G.add_edge(err_msg, str(e)[:50])
        data = nx.node_link_data(G)
        data["links"] = data.get("edges", [])
        if "edges" in data:
            del data["edges"]
        return data

@router.post("/generate-ecosystem")
def generate_ecosystem(payload: IntentPayload):
    graph_data = generate_dynamic_ecosystem_graph(
        payload.intent,
        payload.brief,
        payload.hypothesis_manifest,
    )

    # ── DEV BYPASS CAPTURE: Save snapshot of this run ──
    import pathlib
    capture_dir = pathlib.Path("latest_run_data")
    capture_dir.mkdir(exist_ok=True)
    (capture_dir / "latest_graph.json").write_text(
        json.dumps(graph_data, indent=2), encoding="utf-8"
    )
    
    return {
        "status": "success",
        "graph": graph_data
    }


